In [ ]:
import os
from google.colab import drive
import shutil

# 구글 드라이브 접근
ROOT = "/content/drive"
try:
  drive.mount(ROOT, force_remount=True)
except:
  drive.mount(ROOT)

# 본인 경로에 맞게 수정하면 됨.
PATH = os.path.join(ROOT, "MyDrive/Task/plastic-segmentation/Data")

Mounted at /content/drive


## install

In [ ]:
%%shell
 
pip install cython
# Install pycocotools, the version by default in Colab
# has a bug fixed in https://github.com/cocodataset/cocoapi/pull/354
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

  Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-edop8a0s
  Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-edop8a0s
  Created wheel for pycocotools: filename=pycocotools-2.0-cp37-cp37m-linux_x86_64.whl size=263923 sha256=3801b2ccd2e7cd23bd709241f42538108c27d50bfe9f2d6ef60a79ea38c8adea
  Stored in directory: /tmp/pip-ephem-wheel-cache-20j_vs8e/wheels/e2/6b/1d/344ac773c7495ea0b85eb228bc66daec7400a143a92d36b7b1
Successfully built pycocotools
  Attempting uninstall: pycocotools
    Found existing installation: pycocotools 2.0.3
    Uninstalling pycocotools-2.0.3:
      Successfully uninstalled pycocotools-2.0.3


In [ ]:
%%shell
# download the Penn-Fudan dataset
wget https://www.cis.upenn.edu/~jshi/ped_html/PennFudanPed.zip .
# extract it in the current folder
unzip PennFudanPed.zip
rm PennFudanPed.zip

--2021-12-10 05:27:01--  https://www.cis.upenn.edu/~jshi/ped_html/PennFudanPed.zip
Resolving www.cis.upenn.edu (www.cis.upenn.edu)... 158.130.69.163, 2607:f470:8:64:5ea5::d
Connecting to www.cis.upenn.edu (www.cis.upenn.edu)|158.130.69.163|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 53723336 (51M) [application/zip]
Saving to: ‘PennFudanPed.zip’

PennFudanPed.zip    100%[===================>]  51.23M  68.8MB/s    in 0.7s    

2021-12-10 05:27:02 (68.8 MB/s) - ‘PennFudanPed.zip’ saved [53723336/53723336]

--2021-12-10 05:27:02--  http://./
Resolving . (.)... failed: No address associated with hostname.
wget: unable to resolve host address ‘.’
FINISHED --2021-12-10 05:27:02--
Total wall clock time: 1.0s
Downloaded: 1 files, 51M in 0.7s (68.8 MB/s)
Archive:  PennFudanPed.zip
   creating: PennFudanPed/
  inflating: PennFudanPed/added-object-list.txt  
   creating: PennFudanPed/Annotation/
  inflating: PennFudanPed/Annotation/FudanPed00001.txt  
  inflating: Pen

* structure

```tree
PennFudanPed/
  PedMasks/
    FudanPed00001_mask.png
    FudanPed00002_mask.png
    FudanPed00003_mask.png
    FudanPed00004_mask.png
    ...
  PNGImages/
    FudanPed00001.png
    FudanPed00002.png
    FudanPed00003.png
    FudanPed00004.png
```

```python
from PIL import Image
Image.open('PennFudanPed/PNGImages/FudanPed00001.png')
mask = Image.open('PennFudanPed/PedMasks/FudanPed00001_mask.png')
# each mask instance has a different color, from zero to N, where
# N is the number of instances. In order to make visualization easier,
# let's adda color palette to the mask.
mask.putpalette([
    0, 0, 0, # black background
    255, 0, 0, # index 1 is red
    255, 255, 0, # index 2 is yellow
    255, 153, 0, # index 3 is orange
])
```

In [ ]:
%%shell
# Download TorchVision repo to use some files from
# references/detection
git clone https://github.com/pytorch/vision.git
cd vision
git checkout v0.3.0
 
cp references/detection/utils.py ../
cp references/detection/transforms.py ../
cp references/detection/coco_eval.py ../
cp references/detection/engine.py ../
cp references/detection/coco_utils.py ../
# multi-machine, multi-gpu
cp references/detection/train.py ../

Cloning into 'vision'...
remote: Enumerating objects: 62828, done.
remote: Counting objects: 100% (2597/2597), done.
remote: Compressing objects: 100% (701/701), done.
remote: Total 62828 (delta 2260), reused 2078 (delta 1886), pack-reused 60231
Receiving objects: 100% (62828/62828), 117.04 MiB | 29.10 MiB/s, done.
Resolving deltas: 100% (51034/51034), done.
Note: checking out 'v0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at be376084 version check against PyTorch's CUDA version


In [ ]:
!git clone https://github.com/Proj-Caliber/Waste-Recycling-Image-Segmentation.git/blob/master/config/CaliberDetector.py

Cloning into 'CaliberDetector.py'...
fatal: repository 'https://github.com/Proj-Caliber/Waste-Recycling-Image-Segmentation.git/blob/master/config/CaliberDetector.py/' not found


In [ ]:
if __name__ == "basic-model":
  print("y")

In [ ]:
__name__

'__main__'

In [ ]:
import os
os.getcwd()

'/content'

# init

## general flow

* Dataset
    * CustomDataset
    * DataLoaader
* Model
    * CustomModel
    * train
    * inference
* VSL
    * predict(inference)
    * output

In [ ]:
%load utils.py
%load transforms.py
%load coco_eval.py
%load engine.py 
%load coco_utils.py
%load train.py

In [ ]:
%load_ext autoreload
%autoreload 2

## libraries

In [ ]:
import os
import json
from tqdm import tqdm
from glob import glob

import numpy as np
# import pandas as pd
import cv2 as cv
from PIL import Image

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pycocotools.coco import COCO

import torch
import torch.optim as optim
from torch  import nn, Tensor

from google.colab import drive
import shutil

# 구글 드라이브 접근
ROOT = "/content/drive"
try:
  drive.mount(ROOT, force_remount=True)
except:
  drive.mount(ROOT)

# 본인 경로에 맞게 수정하면 됨.
PATH = os.path.join(ROOT, "MyDrive/Task/plastic-segmentation/Data")
# PATH = os.path.join(ROOT, "MyDrive/Task/plastic-segmentation/Sample_data")

# 구글 드라이브 경로에서 '/content/sample_data/data"로 복사 시
# shutil.copytree(PATH +"/train", "./sample_data/data/train")
# shutil.copytree(PATH +"/test", "./sample_data/data/test")

# BASE = os.getcwd()
# PATH = PATH # gdrive
# PATH = f"{BASE}/sample_data/data"   # colab
# PATH = f"{BASE}/assets/data"        # github

Mounted at /content/drive


## check sorting path process

```python
# author : qkrwjdduf159 <pde159@naver.com>
# version 1
## train
trn_path = f"{PATH}/train/annotation"
file_list = os.listdir(trn_path)

train_files = []
for file in tqdm(file_list):
    dir = trn_path + '/' + file
    json_list = glob(dir + '/' + '*.json')
    train_files.append(json_list)

train_json_list = []
for files in tqdm(train_files):
    for json_file in tqdm(files):
        train_json_list.append(json_file)

## test
tst_PATH = f"{PATH}/test/annotations"
file_list = os.listdir(tst_PATH)

test_files = []
for file in tqdm(file_list):
    dir = tst_PATH + '/' + file
    json_list = glob(dir + '/' + '*.json')
    test_files.append(json_list)

test_json_list = []
for files in tqdm(test_files):
    for json_file in tqdm(files):
        test_json_list.append(json_file)
```


```python
# author : AshbeeKim <ksb.forest@gmail.com>
# version 2
trn = os.path.join(PATH, "train")
tst = os.path.join(PATH, "test")

baseDF = {"kind" : [], "label" : [], "metainfo_id" : [], "feature" : [], "image_path" : [], "annot_path": []}
trn_num, tst_num = 0, 0
for fpath in tqdm([trn, tst]):
    kind = os.path.basename(fpath)
    BDIR = sorted(os.listdir(fpath))    # image, annotation(s)
    for bdir in BDIR:
        for dirs in sorted(os.listdir(jn(fpath, bdir))):
            dpath = jn(fpath, bdir, dirs)
            if bdir.lower()=='image':
                paths = sorted(glob(dpath + "/*.jpg"))
                baseDF['image_path'].extend(paths)
                kinds = [kind for cnt in range(len(paths))]
                baseDF['kind'].extend(kinds)
                if kind=='train' : trn_num += len(paths)
                elif kind=='test' : tst_num += len(paths)
                fnames = [os.path.basename(fname) for fname in paths]
                labels = list(map(lambda x: (x.split('_')[0]), fnames))
                baseDF['label'].extend(labels)
                metaIds = list(map(lambda x: int(x.split('_')[1]), fnames))
                baseDF['metainfo_id'].extend(metaIds)
                feats = list(map(lambda x: int(x.split('_')[-1][:-4]), fnames))
                baseDF['feature'].extend(feats)
            else:
                paths = sorted(glob(dpath + "/*.json"))
                baseDF['annot_path'].extend(paths)
```

## Fix Seeds

In [ ]:
# cotributed by @qkrwjdduf156, @AshbeeKim
# import libraries

import os
import random
import time
import json
from glob import glob
# from tqdm.notebook import tqdm
from tqdm import tqdm

import collections
import numpy as np
import pandas as pd

import cv2 as cv
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import torch
import torchvision
from torchvision.transforms import ToPILImage
from torchvision.transforms import functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

In [ ]:
# Fix randomness
# * ref : https://www.kaggle.com/rluethy/sartorius-torch-mask-r-cnn

def fix_all_seeds(seed):
    np.random.seed(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
    
fix_all_seeds(513610)

data_directory = PATH
DEVICE = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
BATCH_SIZE = 5  # org 1
NUM_EPOCHS = 3  # org 5

# Reduced the train dataset to 5000 rows
TEST = False

# Dataset

masks를 확인하고, 다른 값들을 확인한 결과,, 
* mask 생성 무조건 해야함!!! 
* 형태(모델을 돌리는 방법)는 자유겠지만, 그 각각을 맞추려면 CustomDataset(default)에서 CustomDataset(multi class or process)로 진행되어야 함.

```python
0번째 train 이미지
	 이미지 shape : torch.Size([3, 321, 398])
	 이미지 type : torch.FloatTensor
		dict_keys == 'boxes' :  
			shape : torch.Size([1, 4])
			type : torch.FloatTensor
			tensor([[170.,  21., 319., 311.]])
		dict_keys == 'labels' :  
			shape : torch.Size([1])
			type : torch.LongTensor
			tensor([1])
		dict_keys == 'masks' :  
			shape : torch.Size([1, 321, 398])
			type : torch.ByteTensor
		dict_keys == 'image_id' :  
			shape : torch.Size([1])
			type : torch.LongTensor
			tensor([155])
		dict_keys == 'area' :  
			shape : torch.Size([1])
			type : torch.FloatTensor
			tensor([43210.])
		dict_keys == 'iscrowd' :  
			shape : torch.Size([1])
			type : torch.LongTensor
			tensor([0])

# torch.uint8 -> torch.ByteTensor
# torch.float16 -> torch.HalfTensor
# torch.float, torch.float32 -> torch.FloatTensor
# torch.int16 -> torch.ShortTensor
# torch.int, torch.int32 -> torch.IntTensor
# torch.int64 -> torch.LongTensor
# torch.float64 -> torch.DoubleTensor

# list -> tensor ; torch.as_tensor
# list
```

In [ ]:
%%writefile CaliberDataset.py


import cv2 as cv
from torch.utils.data import Dataset

# 원래 데이터 intance마다
def random_colour_masks(image):
    colours = [[0, 255, 0],[0, 0, 255],[255, 0, 0],[0, 255, 255],[255, 255, 0],[255, 0, 255],[80, 70, 180],[250, 80, 190],[245, 145, 50],[70, 150, 250],[50, 190, 190]]
    r = np.zeros_like(image).astype(np.uint8)
    g = np.zeros_like(image).astype(np.uint8)
    b = np.zeros_like(image).astype(np.uint8)
    r[image == 1], g[image == 1], b[image == 1] = colours[random.randrange(0,10)]
    coloured_mask = np.stack([r, g, b], axis=2)
    return coloured_mask 

def instanceMask(mask, segmentation):
    import cv2 as cv
    mask = mask.copy()
    pts = np.array(segmentation, dtype = np.uint8).reshape(-1, 2)

    pts = np.stack([pts, pts, pts])
    cv.fillPoly(mask, pts, color=(255, 255, 255))
    return mask



class CustomDataset(Dataset):
    def __init__(self, root, transforms = None, target_transforms = None, mode = 'train'):
        self.root = root
        self.transforms = transforms
        self.target_transforms = target_transforms
        self.mode = mode.lower()
        self.infos = self.baseInfos()
        self.imgs, self.annots = self.infos['image_path'], self.infos['annot_path']
        # if self.mode == 'train':
        #     self.imgs, self.masks = blahblah
        self.masks = None

    def __getitem__(self, idx=None):
        '''return tuple(image, target)'''
        image_path = self.imgs[idx]
        # # mask 생성 함수보고 고쳐야 할 듯
        image = cv.imread(image_path)
        image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
        # C, H, W ==  [H, W, C] >> [N+1, H, W, C] >> [N, H, W]
        mask = np.zeros(image.shape, dtype=np.uint8)    
        # # masks = np.zeros(mask_shape, dtype = np.uint8)  
        image = Image.fromarray(image)  # cv to PIL
        # # 굳이 3채널 정보가 필요하지 않다면, (H, W) 만 받아도, instance 공간 할당은 이미 해놓음
        # image = torchvision.transforms(image)    # [C, H, W] 
        # # PIL
        # image = Image.open(image_path).convert("RGB")
        # # image = np.asarray(image)
        # mask = np.zeros(image.shape, dtype=np.uint8)
        
        annot_path = self.annots[idx]
        if self.mode == "train":
            # # train인 경우에만 target['masks'] 처리할 함수가 들어가야 함.
            # mask_shape, target = self.json2annots(annot_path, idx)
            mask, target = self.json2annots(annot_path, idx, mask=mask)
        elif self.mode != "train":
            target = self.json2annots(annot_path, idx)
        # target : dict

        if self.transforms is not None:
            try:
                data = self.transforms(img, target)
                return data
            except:
                if self.transforms is not None:
                    img = self.transforms(img)
                elif self.target_transforms is not None:
                    target = self.target_transforms(target)
                return img, target
        else:
            # target_transform만 따로 들어오는 경우는 고려하지 않았음.
            img = self.preprocess(image)
            return img, target

    def baseInfos(self):
        baseinfos = {"label" : [], "metainfo_id" : [], "feature" : [], "image_path" : [], "annot_path": []}
        
        bpath = os.path.join(self.root, self.mode)
        bdirs = sorted(os.listdir(bpath))   # image, annotation(s)
        
        for bdir in tqdm(bdirs):
            for dirs in sorted(os.listdir(os.path.join(bpath, bdir))):
                dpath = os.path.join(bpath, bdir, dirs)
                
                if bdir.lower()=='image':
                    paths = sorted(glob(dpath + "/*.jpg"))
                    baseinfos['image_path'].extend(paths)
                    fnames = [os.path.basename(fname) for fname in paths]
                    labels = list(map(lambda x: (x.split('_')[0]), fnames))
                    baseinfos['label'].extend(labels)
                    metaIds = list(map(lambda x: int(x.split('_')[1]), fnames))
                    baseinfos['metainfo_id'].extend(metaIds)
                    feats = list(map(lambda x: int(x.split('_')[-1][:-4]), fnames))
                    baseinfos['feature'].extend(feats)
                else:
                    paths = sorted(glob(dpath + "/*.json"))
                    baseinfos['annot_path'].extend(paths)
        return baseinfos

    def preprocess(self, img):
        image = img
        import torchvision.transforms as T
        m, s = np.mean(image, axis = (0, 1)), np.std(image, axis = (0, 1))        
        if self.mode == 'train':
            transform = T.Compose([
                                   T.ToTensor(),
                                   T.Normalize(mean = m, std = s),
            ])
            image = transform(image)
        else:
            transform = T.Compose([
                                   T.Resize(256),
                                   T.ToTensor(),
                                   T.Normalize(mean = m, std = s),
            ])
            image = transform(image)
        return image
    
    def json2annots(self, annot_path, idx, mask=None):
        import cv2 as cv
        with open(annot_path, 'r') as f:
            annot = json.loads(f.read())

        n_objects = len(annot['annotations'])
        W, H = int(annot['images'][0]['width']), int(annot['images'][0]['height'])

        if self.mode == 'train':
            # target = {"boxes" : [], "labels" : [], "masks" : [np.zeros((W, H), dtype = np.uint8)], "image_id" : [], "area" : [], "iscrowd" : []}
            target = {"boxes" : [], "labels" : [], "masks" : [], "image_id" : [], "area" : [], "iscrowd" : []}

            # bbox ground bbox
            gxmin, gymin, gxmax, gymax = 0, 0, 0, 0
            for i in range(n_objects):
                bbox = annot['annotations'][i]['bbox']
                xmin, ymin, width, height = bbox[0],bbox[1],bbox[2],bbox[3]
                xmax, ymax = xmin + width, ymin + height
                target['boxes'].append([xmin, ymin, xmax, ymax])
                # ########## just-in-case(ground_bbox) ##########
                # gxin = xmin if xmin > gxmin else gxmin
                # gymin = ymin if ymin > gymin else gymin
                # gmax = xmax if xmax > gxmax else gxmax
                # gmax = ymax if ymax > gymax else gymax
                # target['boxes'].append([xmin, ymin, xmax, ymax])

                label = annot['annotations'][i]['category_id']
                # torch.ones로 하지 않은 이유는 클래스 정보가 들어가야된다고 판단했기 때문
                target['labels'].append([label])

                # try:
                #     assert mask!=None
                masks = mask.copy() # (H, W, C)
                pts = np.array(annot['annotations'][i]['segmentation'], dtype = np.uint8).reshape(-1, 2)    # (num_of_points,2)
                # org:[C, H, W] >> [H, W, C] >> [N+1, H, W, C] >> [N, H, W]
                pts = np.stack([pts, pts, pts]).astype(int) # (C, num_of_points. 2)
                # mask = 
                cv.fillPoly(masks, pts, (255, 255, 255))    # (H, W, C)

                # segmentation = annot['annotations'][i]['segmentation']
                # mask = instanceMask(mask=self.masks, segmentation=segmentation)
                # mask = self.createMask(annot['annotations'][i]['segmentation'])
                instance = cv.cvtColor(mask, cv.COLOR_RGB2GRAY) # (W, H):instance mase

                target['masks'].append(instance)

                # except:
                    # mask 처리 전, 공간 할당
                    # target['masks'].append(np.zeros((W, H), dtype=np.uint8))

                area = torch.tensor(annot['annotations'][i]['area'], dtype = torch.float32)
                target['area'].append([area])

                iscrowd = torch.tensor(annot['annotations'][i]['iscrowd'], dtype = torch.int64)
                target['iscrowd'].append([iscrowd])
                # ignore = torch.tensor(annot['annotations'][i]['ignore'], dtype = torch.int64)
                # target['ignore'].append([ignore])

            ########################################################## instance id, 필요 시 주석해제 ##########################################################    
            # segmentation에 DataLoader 내에서 어떻게 선언되어 있는지 확인해야 함
            # target['id'] = torch.stack([torch.tensor([i+1]) for i in range(n_objects)]) # shape : (3, 1)
            # ValueError: Expected target boxes to be a tensorof shape [N, 4], got torch.Size([1, 3, 4]).
            ########################################################## type은 맞으나, shape이 맞는지 확신이 없는 부분 ##########################################################
            # torch.Size([3, 2048, 2048])
            # target['boxes'] = torch.as_tensor(target['boxes'], dtype = torch.float32)   
            # shape : (3, 4)
            target['boxes'] = torch.stack([torch.tensor(bbox, dtype = torch.float32) for bbox in target['boxes']])

            # shape : torch.Size([1, 3, 1])
            target['labels'] = torch.as_tensor((target['labels'], ), dtype = torch.int64).squeeze()
            
            # shape : torch.Size([1, 4, 2048, 2048])
            # target['masks'] = torch.as_tensor(target['masks'], dtype = torch.uint8) # (2, H, W) : (C, H, W) >> detection?
            target['masks'] = torch.stack([torch.tensor(mask, dtype = torch.uint8) for mask in target['masks']])  # [3, 2048, 2048] : (num_of_instance, H, W) >> segmentation?
            # mssk 처리 전, 공간 할당

            ########################################################## below ~~ torch.Size([3, 1]) : 각각의 shape도 type도 맞는 것 같음 ##########################################################
            # image_path[index] -> 이미지 자체의 아이디
            target['image_id'] = torch.stack([torch.tensor([idx]) for i in range(n_objects)])   # shape : (3, 1)
            target['area'] = torch.as_tensor(target['area'], dtype = torch.float32) # shape : (1, 3) >> (3, 1)
            target['iscrowd'] = torch.as_tensor(target['iscrowd'], dtype = torch.int64)
            # target['ignore'] = torch.as_tensor(target['ignore'], dtype = torch.int64)
            return target['masks'], target

        else:
            target = {}
            try:
                target['image_id'] = torch.stack([torch.tensor([idx]) for i in range(n_objects)], dtype = torch.int64)
            except:
                target['image_id'] = torch.tensor([idx], dtype=torch.int)
            return target
        # return (n_objects, W, H), target

    # def createMask(self, segmentation=None):
    #     # if self.pipe != "detection":
    #     # elif self.pipi != "detection":
    #     #     img, background = self.imageNmask(image_path, mask_shape)
    #     # bbox
    #     # segmentation
    #     background = self.masks
    #     pts_x, pts_y = [], []
    #     for i in range(len(segmentation)):
    #         pts_x.append(segmentation[i]) if i%2 == 0 else pts_y.append(segmentation[i])
    #     polygon_xy = np.array([(x, y) for (x, y) in zip(pts_x, pts_y)])
    #     cv2.fillPoly(background, np.uint([polygon_xy]), i)
    #     return background
 
    def _labels2category(self, label):
        category = {1 : "PET", 2 : "PS", 3 : "PP", 4 : "PE"}
        return category(label)

    def __len__(self):
        return len(self.imgs)

    # ########## just-in-case ##########
    # # when we need more edas
    # def additional_infos(self):
    #     with open(self.annots[0], 'r') as f:
    #         annot = json.loads(f.read())
    #     metainfo = annot['metainfo']

Writing CaliberDataset.py


## CustomDataset

image segmentation을 위해선 target[boxes, labels, masks] 필수
- 통상 "image_id", 마스크가 속한 이미지 id
- "area", box 면적, pred box, act box IoU 구할 때 필요
- "iscrowd", 작은 물체를 하나의 군집으로 박스처리하여 레이블링 했는지에 관한 여부, 물체가 숨어져있거나, 가려진 경우 사용

In [ ]:
# pip show opencv-python

In [ ]:
# pip install -U opencv-python==4.5.3.56

In [ ]:
# mm = np.zeros((128, 128, 3), dtype=np.uint8)
# print(mm.shape, mm.ndim)

# nn = cv.cvtColor(mm[:,:,:], cv.COLOR_RGB2GRAY)

# print(nn.shape, nn.ndim)

In [ ]:
import cv2 as cv
from torch.utils.data import Dataset

# 원래 데이터 intance마다
def random_colour_masks(image):
    colours = [[0, 255, 0],[0, 0, 255],[255, 0, 0],[0, 255, 255],[255, 255, 0],[255, 0, 255],[80, 70, 180],[250, 80, 190],[245, 145, 50],[70, 150, 250],[50, 190, 190]]
    r = np.zeros_like(image).astype(np.uint8)
    g = np.zeros_like(image).astype(np.uint8)
    b = np.zeros_like(image).astype(np.uint8)
    r[image == 1], g[image == 1], b[image == 1] = colours[random.randrange(0,10)]
    coloured_mask = np.stack([r, g, b], axis=2)
    return coloured_mask 

def instanceMask(mask, segmentation):
    import cv2 as cv
    mask = mask.copy()
    pts = np.array(segmentation, dtype = np.uint8).reshape(-1, 2)

    pts = np.stack([pts, pts, pts])
    cv.fillPoly(mask, pts, color=(255, 255, 255))
    return mask



class CustomDataset(Dataset):
    def __init__(self, root, transforms = None, target_transforms = None, mode = 'train'):
        self.root = root
        self.transforms = transforms
        self.target_transforms = target_transforms
        self.mode = mode.lower()
        self.infos = self.baseInfos()
        self.imgs, self.annots = self.infos['image_path'], self.infos['annot_path']
        # if self.mode == 'train':
        #     self.imgs, self.masks = blahblah
        self.masks = None

    def __getitem__(self, idx=None):
        '''return tuple(image, target)'''
        image_path = self.imgs[idx]
        # # mask 생성 함수보고 고쳐야 할 듯
        image = cv.imread(image_path)
        image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
        # C, H, W ==  [H, W, C] >> [N+1, H, W, C] >> [N, H, W]
        mask = np.zeros(image.shape, dtype=np.uint8)    
        # # masks = np.zeros(mask_shape, dtype = np.uint8)  
        image = Image.fromarray(image)  # cv to PIL
        # # 굳이 3채널 정보가 필요하지 않다면, (H, W) 만 받아도, instance 공간 할당은 이미 해놓음
        # image = torchvision.transforms(image)    # [C, H, W] 
        # # PIL
        # image = Image.open(image_path).convert("RGB")
        # # image = np.asarray(image)
        # mask = np.zeros(image.shape, dtype=np.uint8)
        
        annot_path = self.annots[idx]
        if self.mode == "train":
            # # train인 경우에만 target['masks'] 처리할 함수가 들어가야 함.
            # mask_shape, target = self.json2annots(annot_path, idx)
            mask, target = self.json2annots(annot_path, idx, mask=mask)
        elif self.mode != "train":
            target = self.json2annots(annot_path, idx)
        # target : dict

        if self.transforms is not None:
            try:
                data = self.transforms(img, target)
                return data
            except:
                if self.transforms is not None:
                    img = self.transforms(img)
                elif self.target_transforms is not None:
                    target = self.target_transforms(target)
                return img, target
        else:
            # target_transform만 따로 들어오는 경우는 고려하지 않았음.
            img = self.preprocess(image)
            return img, target

    def baseInfos(self):
        baseinfos = {"label" : [], "metainfo_id" : [], "feature" : [], "image_path" : [], "annot_path": []}
        
        if self.mode == "val":
          bpath = os.path.join(self.root, "train")
        else:
          bpath = os.path.join(self.root, self.mode)
        bdirs = sorted(os.listdir(bpath))   # image, annotation(s)
        
        for bdir in tqdm(bdirs):
            for dirs in sorted(os.listdir(os.path.join(bpath, bdir))):
                dpath = os.path.join(bpath, bdir, dirs)
                
                if bdir.lower()=='image':
                    paths = sorted(glob(dpath + "/*.jpg"))
                    baseinfos['image_path'].extend(paths)
                    fnames = [os.path.basename(fname) for fname in paths]
                    labels = list(map(lambda x: (x.split('_')[0]), fnames))
                    baseinfos['label'].extend(labels)
                    metaIds = list(map(lambda x: int(x.split('_')[1]), fnames))
                    baseinfos['metainfo_id'].extend(metaIds)
                    feats = list(map(lambda x: int(x.split('_')[-1][:-4]), fnames))
                    baseinfos['feature'].extend(feats)
                else:
                    paths = sorted(glob(dpath + "/*.json"))
                    baseinfos['annot_path'].extend(paths)
        return baseinfos

    def preprocess(self, img):
        image = img
        import torchvision.transforms as T
        m, s = np.mean(image, axis = (0, 1)), np.std(image, axis = (0, 1))        
        if self.mode == 'train':
            transform = T.Compose([
                                   T.ToTensor(),
                                   T.Normalize(mean = m, std = s),
            ])
            image = transform(image)
        else:
            transform = T.Compose([
                                   T.Resize(256),
                                   T.ToTensor(),
                                   T.Normalize(mean = m, std = s),
            ])
            image = transform(image)
        return image
    
    def json2annots(self, annot_path, idx, mask=None):
        import cv2 as cv
        with open(annot_path, 'r') as f:
            annot = json.loads(f.read())

        n_objects = len(annot['annotations'])
        W, H = int(annot['images'][0]['width']), int(annot['images'][0]['height'])

        if self.mode == 'train':
            # target = {"boxes" : [], "labels" : [], "masks" : [np.zeros((W, H), dtype = np.uint8)], "image_id" : [], "area" : [], "iscrowd" : []}
            target = {"boxes" : [], "labels" : [], "masks" : [], "image_id" : [], "area" : [], "iscrowd" : []}

            # bbox ground bbox
            gxmin, gymin, gxmax, gymax = 0, 0, 0, 0
            for i in range(n_objects):
                bbox = annot['annotations'][i]['bbox']
                xmin, ymin, width, height = bbox[0],bbox[1],bbox[2],bbox[3]
                xmax, ymax = xmin + width, ymin + height
                target['boxes'].append([xmin, ymin, xmax, ymax])
                # ########## just-in-case(ground_bbox) ##########
                # gxin = xmin if xmin > gxmin else gxmin
                # gymin = ymin if ymin > gymin else gymin
                # gmax = xmax if xmax > gxmax else gxmax
                # gmax = ymax if ymax > gymax else gymax
                # target['boxes'].append([xmin, ymin, xmax, ymax])

                label = annot['annotations'][i]['category_id']
                # torch.ones로 하지 않은 이유는 클래스 정보가 들어가야된다고 판단했기 때문
                target['labels'].append([label])

                # try:
                #     assert mask!=None
                masks = mask.copy() # (H, W, C)
                pts = np.array(annot['annotations'][i]['segmentation'], dtype = np.uint8).reshape(-1, 2)    # (num_of_points,2)
                # org:[C, H, W] >> [H, W, C] >> [N+1, H, W, C] >> [N, H, W]
                pts = np.stack([pts, pts, pts]).astype(int) # (C, num_of_points. 2)
                # mask = 
                cv.fillPoly(masks, pts, (255, 255, 255))    # (H, W, C)

                # segmentation = annot['annotations'][i]['segmentation']
                # mask = instanceMask(mask=self.masks, segmentation=segmentation)
                # mask = self.createMask(annot['annotations'][i]['segmentation'])
                instance = cv.cvtColor(mask, cv.COLOR_RGB2GRAY) # (W, H):instance mase

                target['masks'].append(instance)

                # except:
                    # mask 처리 전, 공간 할당
                    # target['masks'].append(np.zeros((W, H), dtype=np.uint8))

                area = torch.tensor(annot['annotations'][i]['area'], dtype = torch.float32)
                target['area'].append([area])

                iscrowd = torch.tensor(annot['annotations'][i]['iscrowd'], dtype = torch.int64)
                target['iscrowd'].append([iscrowd])
                # ignore = torch.tensor(annot['annotations'][i]['ignore'], dtype = torch.int64)
                # target['ignore'].append([ignore])

            ########################################################## instance id, 필요 시 주석해제 ##########################################################    
            # segmentation에 DataLoader 내에서 어떻게 선언되어 있는지 확인해야 함
            # target['id'] = torch.stack([torch.tensor([i+1]) for i in range(n_objects)]) # shape : (3, 1)
            # ValueError: Expected target boxes to be a tensorof shape [N, 4], got torch.Size([1, 3, 4]).
            ########################################################## type은 맞으나, shape이 맞는지 확신이 없는 부분 ##########################################################
            # torch.Size([3, 2048, 2048])
            # target['boxes'] = torch.as_tensor(target['boxes'], dtype = torch.float32)   
            # shape : (3, 4)
            target['boxes'] = torch.stack([torch.tensor(bbox, dtype = torch.float32) for bbox in target['boxes']])

            # shape : torch.Size([1, 3, 1])
            target['labels'] = torch.as_tensor((target['labels'], ), dtype = torch.int64).squeeze()
            
            # shape : torch.Size([1, 4, 2048, 2048])
            # target['masks'] = torch.as_tensor(target['masks'], dtype = torch.uint8) # (2, H, W) : (C, H, W) >> detection?
            target['masks'] = torch.stack([torch.tensor(mask, dtype = torch.uint8) for mask in target['masks']])  # [3, 2048, 2048] : (num_of_instance, H, W) >> segmentation?
            # mssk 처리 전, 공간 할당

            ########################################################## below ~~ torch.Size([3, 1]) : 각각의 shape도 type도 맞는 것 같음 ##########################################################
            # image_path[index] -> 이미지 자체의 아이디
            target['image_id'] = torch.stack([torch.tensor([idx]) for i in range(n_objects)])   # shape : (3, 1)
            target['area'] = torch.as_tensor(target['area'], dtype = torch.float32) # shape : (1, 3) >> (3, 1)
            target['iscrowd'] = torch.as_tensor(target['iscrowd'], dtype = torch.int64)
            # target['ignore'] = torch.as_tensor(target['ignore'], dtype = torch.int64)
            return target['masks'], target

        else:
            target = {}
            try:
                target['image_id'] = torch.stack([torch.tensor([idx]) for i in range(n_objects)], dtype = torch.int64)
            except:
                target['image_id'] = torch.tensor([idx], dtype=torch.int)
            return target
        # return (n_objects, W, H), target

    # def createMask(self, segmentation=None):
    #     # if self.pipe != "detection":
    #     # elif self.pipi != "detection":
    #     #     img, background = self.imageNmask(image_path, mask_shape)
    #     # bbox
    #     # segmentation
    #     background = self.masks
    #     pts_x, pts_y = [], []
    #     for i in range(len(segmentation)):
    #         pts_x.append(segmentation[i]) if i%2 == 0 else pts_y.append(segmentation[i])
    #     polygon_xy = np.array([(x, y) for (x, y) in zip(pts_x, pts_y)])
    #     cv2.fillPoly(background, np.uint([polygon_xy]), i)
    #     return background
 
    def _labels2category(self, label):
        category = {1 : "PET", 2 : "PS", 3 : "PP", 4 : "PE"}
        return category(label)

    def __len__(self):
        return len(self.imgs)

    # ########## just-in-case ##########
    # # when we need more edas
    # def additional_infos(self):
    #     with open(self.annots[0], 'r') as f:
    #         annot = json.loads(f.read())
    #     metainfo = annot['metainfo']

In [ ]:
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

dataset = CustomDataset(PATH)

idx = random.randint(0, dataset.__len__())

print(f"{idx}번째 train 이미지")

# C, W, H, N
# 
# num_classes, W, H, Batch(num_instance + 1) : mask
print(f"\t 이미지 shape : {dataset[idx][0].shape}\n\t 이미지 type : {dataset[idx][0].type()}")
for k in list(dataset[idx][1].keys()):
     print(f"\t\tdict_keys == '{k}' :  \n\t\t\tshape : {dataset[idx][1][k].shape}\n\t\t\ttype : {dataset[idx][1][k].type()}")
     if k is not "masks":
         print(f"\t\t\t{dataset[idx][1][k]}")

Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth


  0%|          | 0.00/160M [00:00<?, ?B/s]

100%|██████████| 2/2 [00:20<00:00, 10.09s/it]


1882번째 train 이미지
	 이미지 shape : torch.Size([3, 2024, 2024])
	 이미지 type : torch.FloatTensor
		dict_keys == 'boxes' :  
			shape : torch.Size([3, 4])
			type : torch.FloatTensor
			tensor([[ 521.,  244.,  758.,  464.],
        [1065.,  722., 1281.,  947.],
        [ 369.,  565.,  966., 1232.]])
		dict_keys == 'labels' :  
			shape : torch.Size([3])
			type : torch.LongTensor
			tensor([1, 1, 1])
		dict_keys == 'masks' :  
			shape : torch.Size([3, 2024, 2024])
			type : torch.ByteTensor
		dict_keys == 'image_id' :  
			shape : torch.Size([3, 1])
			type : torch.LongTensor
			tensor([[1882],
        [1882],
        [1882]])
		dict_keys == 'area' :  
			shape : torch.Size([3, 1])
			type : torch.FloatTensor
			tensor([[ 40281.5000],
        [ 39518.0000],
        [348839.0000]])
		dict_keys == 'iscrowd' :  
			shape : torch.Size([3, 1])
			type : torch.LongTensor
			tensor([[0],
        [0],
        [0]])


## DataLoader

In [ ]:
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

dataset = CustomDataset(PATH)

idx = random.randint(0, dataset.__len__())

print(f"{idx}번째 train 이미지")

# C, W, H, N
# 
# num_classes, W, H, Batch(num_instance + 1) : mask
print(f"\t 이미지 shape : {dataset[idx][0].shape}\n\t 이미지 type : {dataset[idx][0].type()}")
for k in list(dataset[idx][1].keys()):
     print(f"\t\tdict_keys == '{k}' :  \n\t\t\tshape : {dataset[idx][1][k].shape}\n\t\t\ttype : {dataset[idx][1][k].type()}")
     if k is not "masks":
         print(f"\t\t\t{dataset[idx][1][k]}")

100%|██████████| 2/2 [00:00<00:00, 12.19it/s]


2142번째 train 이미지
	 이미지 shape : torch.Size([3, 2048, 2048])
	 이미지 type : torch.FloatTensor
		dict_keys == 'boxes' :  
			shape : torch.Size([3, 4])
			type : torch.FloatTensor
			tensor([[ 824.,  457., 1204.,  852.],
        [ 394.,  979.,  778., 1364.],
        [1009., 1128., 1354., 1469.]])
		dict_keys == 'labels' :  
			shape : torch.Size([3])
			type : torch.LongTensor
			tensor([3, 3, 3])
		dict_keys == 'masks' :  
			shape : torch.Size([3, 2048, 2048])
			type : torch.ByteTensor
		dict_keys == 'image_id' :  
			shape : torch.Size([3, 1])
			type : torch.LongTensor
			tensor([[2142],
        [2142],
        [2142]])
		dict_keys == 'area' :  
			shape : torch.Size([3, 1])
			type : torch.FloatTensor
			tensor([[117983.5000],
        [116196.5000],
        [ 91739.0000]])
		dict_keys == 'iscrowd' :  
			shape : torch.Size([3, 1])
			type : torch.LongTensor
			tensor([[0],
        [0],
        [0]])


In [ ]:
from engine import train_one_epoch, evaluate
import utils
import transforms as T

data_loader = torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=utils.collate_fn)

# train
images,targets = next(iter(data_loader))
images = list(image for image in images)
targets = [{k: v for k, v in t.items()} for t in targets]
output = model(images,targets)   # Returns losses and detections

# inference
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)           # Returns predictions

/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [ ]:
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

dataset = CustomDataset(PATH)
data_loader = torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=utils.collate_fn)

# train
images,targets = next(iter(data_loader))
images = list(image for image in images)
targets = [{k: v for k, v in t.items()} for t in targets]
output = model(images,targets)   # Returns losses and detections

# inference
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)           # Returns predictions

# /usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
#   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

100%|██████████| 2/2 [00:00<00:00, 13.89it/s]


In [ ]:
predictions

[{'boxes': tensor([], size=(0, 4), grad_fn=<StackBackward0>),
  'labels': tensor([], dtype=torch.int64),
  'scores': tensor([], grad_fn=<IndexBackward0>)},
 {'boxes': tensor([], size=(0, 4), grad_fn=<StackBackward0>),
  'labels': tensor([], dtype=torch.int64),
  'scores': tensor([], grad_fn=<IndexBackward0>)}]

# Model

In [ ]:
import torch
from torch import nn
import torchvision

from engine import train_one_epoch, evaluate
import utils
import transforms as T

def get_transform(train):
    transforms = []
    transforms.append(T.ToTensor())
    if train:
        transforms.append(T.RandomHorizontalFlip(0.5))
    return T.Compose(transforms)

def quick_check(dataset, idx):
    print(f"{idx}번째 {dataset.mode} 이미지")
    print(f"\t 이미지 shape : {dataset[idx][0].shape}\n\t 이미지 type : {dataset[idx][0].type()}")
    for k in list(dataset[idx][1].keys()):
        print(f"\t\tdict_keys == '{k}' :  \n\t\t\tshape : {dataset[idx][1][k].shape}\n\t\t\ttype : {dataset[idx][1][k].type()}")
        if k is not "masks":
            print(f"\t\t\t{dataset[idx][1][k]}\n\n")

def uni_inference(precision, idx):
    print(f"inference no.{idx} : ")
    for k in list(precision[0].keys()):
        print(f"\t{k} : \n\t\t shape : {precision[0][k].shape}\n")

# fastrcnn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

# unet ; torch.hub

# fasterrcnn
import torchvision
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.rpn import AnchorGenerator

# %%writefile ./CaliberDetector.py    # customize 끝내고 run

# detection
from collections import OrderedDict
from torch import nn
from torchvision.ops import MultiScaleRoIAlign
from torchvision._internally_replaced_utils import load_state_dict_from_url
from torchvision.models.detection._utils import overwrite_eps
from torchvision.models.detection.faster_rcnn import FasterRCNN
from torchvision.models.detection.backbone_utils import resnet_fpn_backbone, _validate_trainable_layers

In [ ]:
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor
 
# num_classes == custom data num_classes
def get_model_instance_segmentation(num_classes):
    # load an instance segmentation model pre-trained on COCO,,,resnet50(backbone), fpn(head)
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
 
    # get the number of input features for the classifier
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    # replace the pre-trained head with a new one
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
 
    # now get the number of input features for the mask classifier
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    # and replace the mask predictor with a new one
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask,
                                                       hidden_layer,
                                                       num_classes)
 
    return model

In [ ]:
resize_factor = False # 0.5

# Normalize to resnet mean and std if True.
NORMALIZE = False
RESNET_MEAN = (0.485, 0.456, 0.406)
RESNET_STD = (0.229, 0.224, 0.225)

# No changes tried with the optimizer yet.
MOMENTUM = 0.9
LEARNING_RATE = 0.001
WEIGHT_DECAY = 0.0005

# Changes the confidence required for a pixel to be kept for a mask. 
# Only used 0.5 till now.
# MASK_THRESHOLD = 0.5
# MIN_SCORE = 0.5
# cell type specific thresholds
cell_type_dict = {"astro": 1, "cort": 2, "shsy5y": 3}
mask_threshold_dict = {1: 0.55, 2: 0.75, 3:  0.6}
min_score_dict = {1: 0.55, 2: 0.75, 3: 0.5}

# Use a StepLR scheduler if True. 
USE_SCHEDULER = False

PCT_IMAGES_VALIDATION = 0.075

BOX_DETECTIONS_PER_IMG = 540

In [ ]:
import torchvision
import torch
model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn(pretrained=True)
# model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
PATH = os.path.join(ROOT, "MyDrive/Task/plastic-segmentation/Data")
train = CustomDataset(root =PATH)
data_loader = torch.utils.data.DataLoader(
    train, batch_size=5, shuffle=True, num_workers=2,
    collate_fn=utils.collate_fn
)
# For Training
images,targets = next(iter(data_loader))
images = list(image for image in images)
targets = [{k: v for k, v in t.items()} for t in targets]

output = model(images,targets)   # Returns losses and detections
# For inference
model.eval()
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
predictions = model(x)

def save_general_checkpoint(net, optimizer, NUM_EPOCHS, model_name, purpose, BATCH_SIZE, LOSS):
    EPOCH = NUM_EPOCHS
    PATH = f"./{model_name}_{purpose}_{BATCH_SIZE}_{EPOCH}.pt"
    LOSS = 0.4

    torch.save({
        'epoch':EPOCH,
        'model_state_dict':net.state_dict(),
        'optimizer_state_dict':optimizer.state_dict(),
        'loss':LOSS,
        }, PATH)

Downloading: "https://download.pytorch.org/models/fasterrcnn_mobilenet_v3_large_fpn-fb6a3cc7.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_mobilenet_v3_large_fpn-fb6a3cc7.pth


  0%|          | 0.00/74.2M [00:00<?, ?B/s]

100%|██████████| 2/2 [00:00<00:00, 11.25it/s]


In [ ]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
 
# our dataset has two classes only - background and person : 튜토리얼
# 4 + 1
num_classes = 5
 
# get the model using our helper function
model = get_model_instance_segmentation(num_classes)
# move model to the right device
model.to(device)
 
# construct an optimizer
params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(params, lr=0.005,
                            momentum=0.9, weight_decay=0.0005)
 
# and a learning rate scheduler which decreases the learning rate by
# 10x every 3 epochs
# what if 10x every 6 epochs or 5 epochs?
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer,
                                               step_size=3,
                                               gamma=0.1)

Downloading: "https://download.pytorch.org/models/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth" to /root/.cache/torch/hub/checkpoints/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth


  0%|          | 0.00/170M [00:00<?, ?B/s]

In [ ]:
# No changes tried with the optimizer yet.
from typing import Any, Callable, cast, Dict, List, Optional, Tuple
BATCH_SIZE = 1
NUM_EPOCHS = 5
MOMENTUM = 0.9
LEARNING_RATE = 0.001
WEIGHT_DECAY = 0.0005

PATH = os.path.join(ROOT, "MyDrive/Task/plastic-segmentation/Sample_data")

train_dataset = CustomDataset(root=PATH, mode = 'train')
test_dataset = CustomDataset(root=PATH, mode='train')

# split the dataset in train and test set
torch.manual_seed(1)
indices = torch.randperm(len(train_dataset)).tolist()

train_dataset = torch.utils.data.Subset(train_dataset, indices[:-56]) # 224-56:56:56 이 맞는지는 모르겠습니다.
test_dataset = torch.utils.data.Subset(test_dataset, indices[-56:])

params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(params, lr=LEARNING_RATE, momentum=MOMENTUM, weight_decay=WEIGHT_DECAY)
#optimizer = torch.optim.Adam(params, lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)

from torch.utils.data import DataLoader
# define training and validation data loaders
dl_train = torch.utils.data.DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True, collate_fn=lambda x: tuple(zip(*x)))

dl_val = torch.utils.data.DataLoader(
    test_dataset, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True, collate_fn=lambda x: tuple(zip(*x)))


lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

n_batches, n_batches_val = len(train_dataset), len(test_dataset)

validation_mask_losses = []

for epoch in range(1, NUM_EPOCHS + 1):
    print(f"Starting epoch {epoch} of {NUM_EPOCHS}")

    time_start = time.time()
    loss_accum = 0.0
    loss_mask_accum = 0.0
    loss_classifier_accum = 0.0
    # for batch_idx, (images, targets) in enumerate(dl_train, 1):
    for batch_idx, (images, targets) in enumerate(dl_train):
    
        # Predict
        images = list(image.to(DEVICE) for image in images)
        targets = [{k: v.to(DEVICE) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        print(type(loss_dict), len(loss_dict))
        loss = sum(loss for loss in loss_dict.values())
        
        # Backprop
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        # Logging
        loss_mask = loss_dict['loss_mask'].item()
        loss_accum += loss.item()
        loss_mask_accum += loss_mask
        loss_classifier_accum += loss_dict['loss_classifier'].item()
        
        if batch_idx % 500 == 0:
            print(f"    [Batch {batch_idx:3d} / {n_batches:3d}] Batch train loss: {loss.item():7.3f}. Mask-only loss: {loss_mask:7.3f}.")
                        
    if USE_SCHEDULER:
        lr_scheduler.step()

    # Train losses
    train_loss = loss_accum / n_batches
    train_loss_mask = loss_mask_accum / n_batches
    train_loss_classifier = loss_classifier_accum / n_batches

    # Validation
    val_loss_accum = 0
    val_loss_mask_accum = 0
    val_loss_classifier_accum = 0
    
    with torch.no_grad():
        for batch_idx, (images, targets) in enumerate(dl_val, 1):
            images = list(image.to(DEVICE) for image in images)
            targets = [{k: v.to(DEVICE) for k, v in t.items()} for t in targets]

            val_loss_dict = model(images, targets)
            val_batch_loss = sum(loss for loss in val_loss_dict.values())
            val_loss_accum += val_batch_loss.item()
            val_loss_mask_accum += val_loss_dict['loss_mask'].item()
            val_loss_classifier_accum += val_loss_dict['loss_classifier'].item()

            # save_general_checkpoint(model, optimizer, NUM_EPOCHS, f"iter_{BATCH_SIZE}", "seg", batch_idx, val_loss_accum)

    # Validation losses
    val_loss = val_loss_accum / n_batches_val
    val_loss_mask = val_loss_mask_accum / n_batches_val
    val_loss_classifier = val_loss_classifier_accum / n_batches_val
    elapsed = time.time() - time_start

    validation_mask_losses.append(val_loss_mask)

    torch.save(model.state_dict(), f"pytorch_model-e{epoch}.pth")
    prefix = f"[Epoch {epoch:2d} / {NUM_EPOCHS:2d}]"
    # print(prefix)
    print(f"{prefix} Train mask-only loss: {train_loss_mask:7.3f}, classifier loss {train_loss_classifier:7.3f}")
    print(f"{prefix} Val mask-only loss  : {val_loss_mask:7.3f}, classifier loss {val_loss_classifier:7.3f}")
    print(prefix)
    print(f"{prefix} Train loss: {train_loss:7.3f}. Val loss: {val_loss:7.3f} [{elapsed:.0f} secs]")
    # print(prefix)

100%|██████████| 2/2 [00:00<00:00, 94.07it/s]


Starting epoch 1 of 5
<class 'dict'> 5
    [Batch   0 / 168] Batch train loss:   3.450. Mask-only loss:   1.293.
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<class 'dict'> 5
<cl